# AppProject ApplicationSet
# Generates Namespaces and AppProjects from cluster values files
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appprojects
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/your-org/your-repo.git
        revision: HEAD
        files:
          - path: "apps/values/trino-deployments/*.yaml"
  template:
    metadata:
      name: 'setup-{{.trinoDeployment.name}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: '{{.git.repoURL}}'
        targetRevision: '{{.git.targetRevision}}'
        path: apps/bootstrap
        helm:
          releaseName: 'setup-{{.trinoDeployment.name}}'
          values: |
            namespace: {{.appProject.name}}
            deploymentName: {{.trinoDeployment.name}}
            clusterName: {{.cluster.name}}
            appProject:
              name: {{.appProject.name}}
              description: {{.appProject.description}}
              sourceRepos:
                {{- range .appProject.sourceRepos}}
                - {{.}}
                {{- end}}
              destinations:
                {{- range .appProject.destinations}}
                - namespace: {{.namespace}}
                  server: {{.server}}
                {{- end}}
              clusterResourceWhitelist:
                {{- range .appProject.clusterResourceWhitelist}}
                - group: {{.group}}
                  kind: {{.kind}}
                {{- end}}
              namespaceResourceWhitelist:
                {{- range .appProject.namespaceResourceWhitelist}}
                - group: {{.group}}
                  kind: {{.kind}}
                {{- end}}
              orphanedResources:
                warn: {{.appProject.orphanedResources.warn}}
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

# Made with Bob